### ISSUE TITLE
server tror att ett meddelande är flera

### ISSUE THREAD

**Issue by KylarJordgubbar** [TinyKenny/Dolphin#3]
exempel:
![bugg](https://cloud.githubusercontent.com/assets/10535033/19785409/8a2ca706-9c99-11e6-8851-d6b8c3c4be55.PNG)

**Comment by KylarJordgubbar** [comment]
detta kanske kan lösas av att byta ut notify() mot notifyall() och fixa lite mer

**Comment by TinyKenny** [comment]
Löst i ServerBranch, kommer fixas i Master när jag har en hyfsat stabil build av servern
