### ISSUE TITLE
annan error för linux

### ISSUE THREAD

**Issue by KylarJordgubbar** [TinyKenny/Dolphin#4]
![screenshot at 2016-11-07 21-20-08](https://cloud.githubusercontent.com/assets/10535033/20074447/930e041a-a530-11e6-9f9f-8238a541bdc5.png)
när man kör "/quit" raisas detta error i servern, tror att det bara är så som linux tolkar det.

**Comment by TinyKenny** [comment]
Det är bara på Linux det sker. Det kommer fixas i version 0.0.1.x, som kommer släppas i eftermiddag, efter lite testande
